### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jsmnwltrs** [nss-evening-cohort-8/chatty-bottle-openers#15]
### User Story
As a developer, in order to build the application, I need to setup files with boilerplate code.

### Development
- create below files and folders.
- add boilerplate code and bootstrap setup to html file.
- link main.css on html file and add script tags for all javascript files with the module type. (add a background color and console logs to make sure files are linked properly)
<img width="221" alt="template" src="https://user-images.githubusercontent.com/41760060/46641750-e1b2d200-cb38-11e8-89ae-ab8753643d0d.PNG">

### Acceptance Criteria
- all files and folders are created.
- boilerplate and bootstrap setup code is in html file.
- files are linked properly
- console logs have been removed before merging to master

**Comment by zoeames** [comment]
this ticket will be a little hard to test if you remove the console.logs before merging in.  For this ticket only it is ok if you leave the console.logs in when you merge.  as the other tickets are worked on those console.logs will go away
