### ISSUE TITLE
Message Limit

### ISSUE THREAD

**Issue by MaryRys** [nss-evening-cohort-8/chatty-bottle-openers#16]
# User Experience
As a user, I can add as many messages as I want and only the last 10 will be visible.

# Dev Notes
The main square div will only print indexes 0-9 from the messages array. There needs to be a function that gets all the elements by class name and loops through them. A counter variable should increment by 1 in the loop. An if statement will specify if the counter is greater than 10, use .item method to remove the 0 index.

# Acceptance Criteria
* New messages will be added to the top of the list.
* Once 10 messages have been added, the oldest message will be removed and the new message will be added.

**Comment by zoeames** [comment]
Your JSON data only has 5 messages in it.  So when you get to message 20 the last 15 messages should come from the input.  Did you mean to say only print indexes 0-19 from the messages array?

**Comment by jsmnwltrs** [comment]
This ticket might need some tweeking. I realized that the messages printing to the square container are just strings. They are not adding to an array. If we make them an array of strings, we would have to modify other functions we already have working.
