### ISSUE TITLE
Style of Page

### ISSUE THREAD

**Issue by dragonxrage88** [nss-evening-cohort-8/chatty-bottle-openers#17]
# User Story
As a user, I want to see a CSS on the page, so that I can see the best looking chat website. 

# Acceptance Criteria
**When** a user navigates to the site
**Then** the user should see all changes to background.

# Technical Notes
* default colors should be windows 95/98 style 
* should have a blue navbar. 
* should have a black and white text and background.
* and should have large text.

**Comment by jsmnwltrs** [comment]
![windows](https://user-images.githubusercontent.com/41760060/46829461-857fc600-cd63-11e8-8612-d31e961f6944.png)
