### ISSUE TITLE
Data - JSON, XHR and PrintToDom setup

### ISSUE THREAD

**Issue by jsmnwltrs** [nss-evening-cohort-8/chatty-bottle-openers#19]
### User Story
As a developer, in order to develop the functionality of the application, I need some data.

### Development
- on the chatData.json file, add an array of objects that has at least five messages. Validate it as well to make sure there are no syntax errors. (see example in comments below).
- on the chatData.js file, create an XHR request that retrieves the data. (use console log to make sure it's working)
- create a printToDom function on the util.js file.

### Acceptance Criteria
- json file is setup with at least 5 messages.
- XHR request is working
- PrintToDom function is working
- remove console logs before merging

**Comment by jsmnwltrs** [comment]
{
    "chatMessages":  [
      {
        "username": "User1",
        "message": "Hello there!"
    },
  {
        "username": "User2",
        "message": "How are you?"
    }
  ]
}

**Comment by zoeames** [comment]
what about the timestamps?
