### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by MaryRys** [nss-evening-cohort-8/chatty-bottle-openers#20]
# User Experience
As a user, I will be able to select my name from the dropdown list, and submit a new message which will show my name.

# Dev Notes
* create a header element that says **Users:** on the html file. (this should be done after the navbar and before the messages container.)
* create a div container with the ID of "users"
* In the users container, create 4 radio buttons that display usernames. (It can be our names)
* give a unique ID to each of the radio buttons.
* in the arrayBuilder function that prints the messages from the input field, include the username that is selected by the radio buttons. Use the ID to get the innerHTML string of that button.

# Acceptance Criteria
* Users appear in their own container on the screen with a header above it and can be selected by using radio buttons.
* Message that prints from the input field displays the user that was selected.

**Comment by MaryRys** [comment]
https://getbootstrap.com/docs/4.0/components/dropdowns/

**Comment by zoeames** [comment]
According to #19 a message object looks something like this:
```{
"username": "User1",
"message": "Hello there!"
},```

This ticket makes no mention of usernames.  How are you going to tie the users in the users object to a username that can go in a message?

Hint:  maybe users should be an array of objects?
