### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by MaryRys** [nss-evening-cohort-8/chatty-bottle-openers#26]
# User Experience
As a user, I will see a check box on the navbar that can be clicked to show dark mode.

# Dev Notes
* Dark mode will change the background color to a dark grey and the text color to a whiteish color. 
* Add event listeners to listen for 'click' which runs a function to add this style.

# Acceptance Criteria
* When I click the checkbox, the background and font colors will go to dark mode.
* Unchecking the box removes this style.

**Comment by zoeames** [comment]
This ticket should be broken into 2 - one for dark mode and one for large text
