### ISSUE TITLE
Modal BootStrap (Custom themes)

### ISSUE THREAD

**Issue by dragonxrage88** [nss-evening-cohort-8/chatty-bottle-openers#28]
# User Story
As a user, I want to see a  Modal alert that will contain the color picker to make custom themes. I should be able edit to the background color of the Square, and/or text color.

# Acceptance Criteria
When I click the custom theme button, a modal popup appears allowing me to select two different colors for background of square, and text of square.

# Technical Notes
- Color picker
- Modal bootstrap
- Event listener

**Comment by zoeames** [comment]
This ticket should be rolled into #29.  Currently this ticket and the other one have contradictory information about how you are editing
